name: Deploy Heroku

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.16
    - name: Build     
      run: ./build.sh --target=build
    - name: Publish     
      run: ./build.sh --target=publish
    - uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "gringotts-hasanbasaran"
        heroku_email: "basaranhasan@outlook.com.tr"
        usedocker: true